spring.application.name=Application Tracking System

#Database Credentials
spring.datasource.url=jdbc:mysql://localhost:3306/ats_db
spring.datasource.username=root
spring.datasource.password=NewPassword@123

#SQL Query Generation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Upload Directory
file.upload-dir=uploads/resumes
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.jpa.open-in-view=false
server.error.include-message=never